spring:
  application:
    name: hairmony
  datasource:
    url: jdbc:postgresql://localhost:5432/hairmonydb
    username: postgres
    password: 200361816
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id.new_generator_mappings: true
  web:
    cors:
      enabled: true
      mappings:
        anyName:
          paths:
            - /api/**
          allowed-origins: "http://localhost:4000"
          allowed-methods: GET, POST, PUT, DELETE, OPTIONS
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600

jwt:
  secret: MyJwtSecretKeyForHairmony
  expiration: 3600000  # Token expiry time in milliseconds (1 hour)

server:
  port: 8443  # Default port

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate: INFO
